In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [6]:
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [7]:
df.tail(10)

RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
9990       9991    15798964   Nkemakonam          714   Germany    Male   33   
9991       9992    15769959  Ajuluchukwu          597    France  Female   53   
9992       9993    15657105  Chukwualuka          726     Spain    Male   36   
9993       9994    15569266       Rahman          644    France    Male   28   
9994       9995    15719294         Wood          800    France  Female   29   
9995       9996    15606229     Obijiaku          771    France    Male   39   
9996       9997    15569892    Johnstone          516    France    Male   35   
9997       9998    15584532          Liu          709    France  Female   36   
9998       9999    15682355    Sabbatini          772   Germany    Male   42   
9999      10000    15628319       Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9990       3   35016.60              1          1               0   
9991       4   88381.21              1          1               0   
9992       2       0.00              1          1               0   
9993       7  155060.41              1          1               0   
9994       2       0.00              2          0               0   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9990         53667.08       0  
9991         69384.71       1  
9992        195192.40       0  
9993         29179.52       0  
9994        167773.55       0  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [9]:
df.shape

(10000, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [12]:
df.duplicated().sum()

0

In [15]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [16]:
df['Exited'].value_counts()
# zero who have not left 
# one who have left

0    7963
1    2037
Name: Exited, dtype: int64

In [17]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [18]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [19]:
df.drop(columns = ['RowNumber','CustomerId','Surname'], inplace=True )

In [20]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [21]:
df = pd.get_dummies(df, columns=['Geography','Gender'])

In [23]:
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                0              1            0  
1                  0                1              1            0  
2                  0                0              1            0  
3                  0                0              1            0  
4                  0                1              1            0

In [41]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [42]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0

In [44]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [52]:
X_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
2694          628   29       3  113146.98              2          0   
5140          626   29       4  105767.28              2          0   
2568          612   47       6  130024.87              1          1   
3671          646   52       6  111739.40              2          0   
7427          714   33       8  122017.19              1          0   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
2694               1        124749.08                 0                  1   
5140               0         41104.82                 1                  0   
2568               1         45750.21                 0                  1   
3671               1         68367.18                 0                  1   
7427               0        162515.17                 0                  0   

      Geography_Spain  Gender_Female  Gender_Male  
2694                0              0            1  
5140                0              1            0  
2568                0              1            0  
3671                0              1            0  
7427                1              0            1

In [53]:
y_train.head()

2694    0
5140    0
2568    1
3671    0
7427    0
Name: Exited, dtype: int64

In [54]:
X_test.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9953          550   47       2       0.00              2          1   
3850          680   34       3  143292.95              1          1   
4962          531   42       2       0.00              2          0   
3886          710   34       8  147833.30              2          0   
5437          543   30       6   73481.05              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
9953               1         97057.28                 1                  0   
3850               0         66526.01                 1                  0   
4962               1         90537.47                 1                  0   
3886               1          1561.58                 0                  1   
5437               1        176692.65                 0                  1   

      Geography_Spain  Gender_Female  Gender_Male  
9953                0              0            1  
3850                0              0            1  
4962                0              1            0  
3886                0              0            1  
5437                0              0            1

In [55]:
y_test

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [34]:
# Standardization is Z-Score normalisation
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ..., -0.57273139,
        -0.91509065,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.57273139,
         1.09278791, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ..., -0.57273139,
         1.09278791, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.57273139,
         1.09278791, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.57273139,
         1.09278791, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ..., -0.57273139,
        -0.91509065,  0.91509065]])

In [ ]:
X_test_scaled

array([[-1.03768121,  0.77498705, -1.0482813 , ..., -0.57273139,
        -0.91509065,  0.91509065],
       [ 0.30708683, -0.46686456, -0.70174202, ..., -0.57273139,
        -0.91509065,  0.91509065],
       [-1.23422423,  0.29735181, -1.0482813 , ..., -0.57273139,
         1.09278791, -1.09278791],
       ...,
       [-0.86182692, -0.46686456,  1.72403288, ...,  1.74601919,
        -0.91509065,  0.91509065],
       [-0.30323097, -0.84897275, -1.0482813 , ..., -0.57273139,
         1.09278791, -1.09278791],
       [ 0.04847759,  1.25262228,  1.3774936 , ..., -0.57273139,
        -0.91509065,  0.91509065]])

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Importing tensorflow
import tensorflow as tf

In [ ]:
# Importing Keras
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(3,activation='sigmoid',input_dim=13))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 42        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [ ]:
# batch_size = 32
# %time fit = model.fit(X_train_scaled, y_train, epochs=10, batch_size=batch_size, validation_split=0.2)
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.6784
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.5525
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4995
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4764
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4642
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4558
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4490
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4433
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4384
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4343


In [ ]:
model.layers[0].get_weights()

[array([[ 2.56161064e-01,  8.81048813e-02, -4.24809270e-02],
        [-7.26310372e-01, -2.05179453e+00,  4.46002603e-01],
        [-2.04104543e-01,  2.38166377e-02, -2.36304283e-01],
        [-5.73923707e-01, -3.86942595e-01, -1.42430456e-03],
        [ 5.69474995e-01, -4.78040613e-02, -4.53610390e-01],
        [-2.09709406e-01,  6.40665293e-02, -9.92040485e-02],
        [ 1.06656575e+00,  6.62729979e-01, -1.19961476e+00],
        [-4.64894660e-02, -8.44687000e-02, -1.52807340e-01],
        [ 1.89888239e-01,  4.04653013e-01, -3.99162799e-01],
        [-1.09130405e-01, -2.67702401e-01,  7.07734406e-01],
        [ 2.07003981e-01,  3.40034425e-01, -7.66446963e-02],
        [-1.11570463e-01, -5.98254085e-01,  7.57273361e-02],
        [ 3.22196007e-01, -6.36945292e-02, -5.85124969e-01]], dtype=float32),
 array([ 0.11043406,  0.67600244, -0.41987452], dtype=float32)]

In [ ]:
model.layers[1].get_weights()

[array([[-0.43251288],
        [-1.4942483 ],
        [ 0.449022  ]], dtype=float32), array([-0.58620185], dtype=float32)]

In [ ]:
# model.layers[2].get_weights()
# IndexError: list index out of range

In [ ]:
y_log = model.predict(X_test_scaled)
y_log

63/63 [==============================] - 0s 1ms/step


array([[0.11677621],
       [0.1520441 ],
       [0.13241777],
       ...,
       [0.08132821],
       [0.14219286],
       [0.35391057]], dtype=float32)

In [ ]:
y_pred = np.where(y_log > 0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7925