Import the Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
# Loading train and test data
trainData =  pd.read_csv('train_LR.csv')
trainData.head()

MaritalStatus  YearlyIncome  TotalChildren  ChildrenAtHome  HouseOwnerFlag  \
0              1        130000              4               5               1   
1              1        110000              1               1               1   
2              1         60000              2               0               0   
3              1         70000              5               4               1   
4              0         90000              3               2               0   

   NumberCarsOwned  Age  CycleBuyer  
0                4   63           0  
1                4   54           0  
2                2   56           0  
3                3   53           0  
4                1   58           0

In [6]:
# Creating the dependent and independent variables for the training module(X_train, y_train)
y_train = trainData['CycleBuyer']
X_train = trainData.drop('CycleBuyer', axis=1)
X_train.head()

MaritalStatus  YearlyIncome  TotalChildren  ChildrenAtHome  HouseOwnerFlag  \
0              1        130000              4               5               1   
1              1        110000              1               1               1   
2              1         60000              2               0               0   
3              1         70000              5               4               1   
4              0         90000              3               2               0   

   NumberCarsOwned  Age  
0                4   63  
1                4   54  
2                2   56  
3                3   53  
4                1   58

In [7]:
y_train.head()

0    0
1    0
2    0
3    0
4    0
Name: CycleBuyer, dtype: int64

In [9]:
testData = pd.read_csv('test_LR.csv')
testData.head()

MaritalStatus  YearlyIncome  TotalChildren  ChildrenAtHome  HouseOwnerFlag  \
0              1         70000              4               2               1   
1              0         30000              4               0               0   
2              0         10000              2               2               1   
3              1         70000              4               0               0   
4              1         30000              0               0               1   

   NumberCarsOwned  Age  CycleBuyer  
0                1   62           0  
1                2   66           0  
2                0   43           0  
3                0   43           1  
4                2   34           0

In [12]:
y_test = testData['CycleBuyer']
X_test = testData.drop('CycleBuyer', axis=1)
X_test.head()

MaritalStatus  YearlyIncome  TotalChildren  ChildrenAtHome  HouseOwnerFlag  \
0              1         70000              4               2               1   
1              0         30000              4               0               0   
2              0         10000              2               2               1   
3              1         70000              4               0               0   
4              1         30000              0               0               1   

   NumberCarsOwned  Age  
0                1   62  
1                2   66  
2                0   43  
3                0   43  
4                2   34

In [13]:
y_test.head()

0    0
1    0
2    0
3    1
4    0
Name: CycleBuyer, dtype: int64

In [17]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred_train = model.predict(X_train)
y_pred_train

array([1, 1, 0, ..., 0, 1, 0])

In [19]:
y_pred_test = model.predict(X_test)
y_pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
# Creating classification report
classificationReport = classification_report(y_test,y_pred_test)
print("Classification report \n",classificationReport)

Classification report 
               precision    recall  f1-score   support

           0       0.52      0.69      0.59      3108
           1       0.52      0.34      0.41      2992

    accuracy                           0.52      6100
   macro avg       0.52      0.52      0.50      6100
weighted avg       0.52      0.52      0.50      6100



In [25]:
# Creating confusion matrix
confusion_matrix(y_test,y_pred_test)

array([[2139,  969],
       [1961, 1031]])

In [26]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_test).ravel()
(tn,fp, fn, tp)

(2139, 969, 1961, 1031)